#ifndef EOS_STIFFENEDGAS___STIFFENEDGASACCSERVICESCIHOOKMACROS_H
#define EOS_STIFFENEDGAS___STIFFENEDGASACCSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED)
#include "SciHook.h"
#include "eos/stiffenedgas/__StiffenedGasAccServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED)
#define SCIHOOK_DECLARE_EOS_STIFFENEDGAS_STIFFENEDGASACC_EVENTS \
private:\
 size_t APPLYEOSWITHSUPPORT_BEFORE;\
 size_t APPLYEOSWITHSUPPORT_AFTER;\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_STIFFENEDGAS_STIFFENEDGASACC_EVENTS \
APPLYEOSWITHSUPPORT_BEFORE = SciHook::register_base_event("StiffenedGasAcc.ApplyEOSWithSupport.Before");\
APPLYEOSWITHSUPPORT_AFTER = SciHook::register_base_event("StiffenedGasAcc.ApplyEOSWithSupport.After");\
INITEOS_BEFORE = SciHook::register_base_event("StiffenedGasAcc.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("StiffenedGasAcc.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("StiffenedGasAcc.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("StiffenedGasAcc.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("StiffenedGasAcc.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("StiffenedGasAcc.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_STIFFENEDGAS_STIFFENEDGASACC_EVENTS
#define SCIHOOK_INITIALIZE_EOS_STIFFENEDGAS_STIFFENEDGASACC_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOSWITHSUPPORT_DISABLED)
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOSWITHSUPPORT_BEFORE \
std::shared_ptr<StiffenedGasAccApplyEOSWithSupportExecutionContext> ctx(new StiffenedGasAccApplyEOSWithSupportExecutionContext("ApplyEOSWithSupportExecutionContext", &acc_context));\
SciHook::trigger(APPLYEOSWITHSUPPORT_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOSWITHSUPPORT_AFTER SciHook::trigger(APPLYEOSWITHSUPPORT_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOSWITHSUPPORT_BEFORE
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOSWITHSUPPORT_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_INITEOS_BEFORE \
std::shared_ptr<StiffenedGasAccInitEOSExecutionContext> ctx(new StiffenedGasAccInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOS_BEFORE \
std::shared_ptr<StiffenedGasAccApplyEOSExecutionContext> ctx(new StiffenedGasAccApplyEOSExecutionContext("ApplyEOSExecutionContext", env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_DISABLED) && not defined(SCIHOOK_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYONECELLEOS_BEFORE \
std::shared_ptr<StiffenedGasAccApplyOneCellEOSExecutionContext> ctx(new StiffenedGasAccApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_STIFFENEDGAS_STIFFENEDGASACC_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_STIFFENEDGAS___STIFFENEDGASACCSERVICESCIHOOKMACROS_H
