#ifndef EOS_PERFECTGAS___PERFECTGASACCSERVICESCIHOOKMACROS_H
#define EOS_PERFECTGAS___PERFECTGASACCSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED)
#include "SciHook.h"
#include "eos/perfectgas/__PerfectGasAccServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED)
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASACC_EVENTS \
private:\
 size_t APPLYEOSWITHSUPPORT_BEFORE;\
 size_t APPLYEOSWITHSUPPORT_AFTER;\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASACC_EVENTS \
APPLYEOSWITHSUPPORT_BEFORE = SciHook::register_base_event("PerfectGasAcc.ApplyEOSWithSupport.Before");\
APPLYEOSWITHSUPPORT_AFTER = SciHook::register_base_event("PerfectGasAcc.ApplyEOSWithSupport.After");\
INITEOS_BEFORE = SciHook::register_base_event("PerfectGasAcc.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("PerfectGasAcc.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("PerfectGasAcc.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("PerfectGasAcc.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("PerfectGasAcc.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("PerfectGasAcc.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASACC_EVENTS
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASACC_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOSWITHSUPPORT_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOSWITHSUPPORT_BEFORE \
std::shared_ptr<PerfectGasAccApplyEOSWithSupportExecutionContext> ctx(new PerfectGasAccApplyEOSWithSupportExecutionContext("ApplyEOSWithSupportExecutionContext", &acc_context, env));\
SciHook::trigger(APPLYEOSWITHSUPPORT_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOSWITHSUPPORT_AFTER SciHook::trigger(APPLYEOSWITHSUPPORT_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOSWITHSUPPORT_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOSWITHSUPPORT_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_INITEOS_BEFORE \
std::shared_ptr<PerfectGasAccInitEOSExecutionContext> ctx(new PerfectGasAccInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOS_BEFORE \
std::shared_ptr<PerfectGasAccApplyEOSExecutionContext> ctx(new PerfectGasAccApplyEOSExecutionContext("ApplyEOSExecutionContext", env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACC_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYONECELLEOS_BEFORE \
std::shared_ptr<PerfectGasAccApplyOneCellEOSExecutionContext> ctx(new PerfectGasAccApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACC_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_PERFECTGAS___PERFECTGASACCSERVICESCIHOOKMACROS_H
