#ifndef EOS_PERFECTGAS___PERFECTGASPACCSERVICESCIHOOKMACROS_H
#define EOS_PERFECTGAS___PERFECTGASPACCSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_DISABLED)
#include "SciHook.h"
#include "eos/perfectgas/__PerfectGasPAccServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_DISABLED)
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASPACC_EVENTS \
private:\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASPACC_EVENTS \
INITEOS_BEFORE = SciHook::register_base_event("PerfectGasPAcc.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("PerfectGasPAcc.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("PerfectGasPAcc.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("PerfectGasPAcc.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("PerfectGasPAcc.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("PerfectGasPAcc.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASPACC_EVENTS
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASPACC_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_INITEOS_BEFORE \
std::shared_ptr<PerfectGasPAccInitEOSExecutionContext> ctx(new PerfectGasPAccInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYEOS_BEFORE \
std::shared_ptr<PerfectGasPAccApplyEOSExecutionContext> ctx(new PerfectGasPAccApplyEOSExecutionContext("ApplyEOSExecutionContext", &vars, env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASPACC_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYONECELLEOS_BEFORE \
std::shared_ptr<PerfectGasPAccApplyOneCellEOSExecutionContext> ctx(new PerfectGasPAccApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASPACC_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_PERFECTGAS___PERFECTGASPACCSERVICESCIHOOKMACROS_H
