#ifndef EOS_PERFECTGAS___PERFECTGASNACCSERVICESCIHOOKMACROS_H
#define EOS_PERFECTGAS___PERFECTGASNACCSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_DISABLED)
#include "SciHook.h"
#include "eos/perfectgas/__PerfectGasNAccServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_DISABLED)
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASNACC_EVENTS \
private:\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASNACC_EVENTS \
INITEOS_BEFORE = SciHook::register_base_event("PerfectGasNAcc.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("PerfectGasNAcc.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("PerfectGasNAcc.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("PerfectGasNAcc.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("PerfectGasNAcc.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("PerfectGasNAcc.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASNACC_EVENTS
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASNACC_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_INITEOS_BEFORE \
std::shared_ptr<PerfectGasNAccInitEOSExecutionContext> ctx(new PerfectGasNAccInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYEOS_BEFORE \
std::shared_ptr<PerfectGasNAccApplyEOSExecutionContext> ctx(new PerfectGasNAccApplyEOSExecutionContext("ApplyEOSExecutionContext", &vars, env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASNACC_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYONECELLEOS_BEFORE \
std::shared_ptr<PerfectGasNAccApplyOneCellEOSExecutionContext> ctx(new PerfectGasNAccApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASNACC_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_PERFECTGAS___PERFECTGASNACCSERVICESCIHOOKMACROS_H
