#ifndef EOS_PERFECTGAS___PERFECTGASACCWITHSUPPORTSERVICESCIHOOKMACROS_H
#define EOS_PERFECTGAS___PERFECTGASACCWITHSUPPORTSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED)
#include "SciHook.h"
#include "eos/perfectgas/__PerfectGasAccWithSupportServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED)
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_EVENTS \
private:\
 size_t APPLYEOSWITHSUPPORT_BEFORE;\
 size_t APPLYEOSWITHSUPPORT_AFTER;\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_EVENTS \
APPLYEOSWITHSUPPORT_BEFORE = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyEOSWithSupport.Before");\
APPLYEOSWITHSUPPORT_AFTER = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyEOSWithSupport.After");\
INITEOS_BEFORE = SciHook::register_base_event("PerfectGasAccWithSupport.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("PerfectGasAccWithSupport.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("PerfectGasAccWithSupport.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_EVENTS
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOSWITHSUPPORT_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOSWITHSUPPORT_BEFORE \
std::shared_ptr<PerfectGasAccWithSupportApplyEOSWithSupportExecutionContext> ctx(new PerfectGasAccWithSupportApplyEOSWithSupportExecutionContext("ApplyEOSWithSupportExecutionContext", &acc_context));\
SciHook::trigger(APPLYEOSWITHSUPPORT_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOSWITHSUPPORT_AFTER SciHook::trigger(APPLYEOSWITHSUPPORT_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOSWITHSUPPORT_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOSWITHSUPPORT_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_INITEOS_BEFORE \
std::shared_ptr<PerfectGasAccWithSupportInitEOSExecutionContext> ctx(new PerfectGasAccWithSupportInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOS_BEFORE \
std::shared_ptr<PerfectGasAccWithSupportApplyEOSExecutionContext> ctx(new PerfectGasAccWithSupportApplyEOSExecutionContext("ApplyEOSExecutionContext", env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYONECELLEOS_BEFORE \
std::shared_ptr<PerfectGasAccWithSupportApplyOneCellEOSExecutionContext> ctx(new PerfectGasAccWithSupportApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASACCWITHSUPPORT_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_PERFECTGAS___PERFECTGASACCWITHSUPPORTSERVICESCIHOOKMACROS_H
