#ifndef EOS_PERFECTGAS___PERFECTGASWITHSUPPORTSERVICESCIHOOKMACROS_H
#define EOS_PERFECTGAS___PERFECTGASWITHSUPPORTSERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED)
#include "SciHook.h"
#include "eos/perfectgas/__PerfectGasWithSupportServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED)
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_EVENTS \
private:\
 size_t APPLYEOSWITHSUPPORT_BEFORE;\
 size_t APPLYEOSWITHSUPPORT_AFTER;\
 size_t INITEOS_BEFORE;\
 size_t INITEOS_AFTER;\
 size_t APPLYEOS_BEFORE;\
 size_t APPLYEOS_AFTER;\
 size_t APPLYONECELLEOS_BEFORE;\
 size_t APPLYONECELLEOS_AFTER;
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_EVENTS \
APPLYEOSWITHSUPPORT_BEFORE = SciHook::register_base_event("PerfectGasWithSupport.ApplyEOSWithSupport.Before");\
APPLYEOSWITHSUPPORT_AFTER = SciHook::register_base_event("PerfectGasWithSupport.ApplyEOSWithSupport.After");\
INITEOS_BEFORE = SciHook::register_base_event("PerfectGasWithSupport.InitEOS.Before");\
INITEOS_AFTER = SciHook::register_base_event("PerfectGasWithSupport.InitEOS.After");\
APPLYEOS_BEFORE = SciHook::register_base_event("PerfectGasWithSupport.ApplyEOS.Before");\
APPLYEOS_AFTER = SciHook::register_base_event("PerfectGasWithSupport.ApplyEOS.After");\
APPLYONECELLEOS_BEFORE = SciHook::register_base_event("PerfectGasWithSupport.ApplyOneCellEOS.Before");\
APPLYONECELLEOS_AFTER = SciHook::register_base_event("PerfectGasWithSupport.ApplyOneCellEOS.After");
#else
#define SCIHOOK_DECLARE_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_EVENTS
#define SCIHOOK_INITIALIZE_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_EVENTS
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOSWITHSUPPORT_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOSWITHSUPPORT_BEFORE \
std::shared_ptr<PerfectGasWithSupportApplyEOSWithSupportExecutionContext> ctx(new PerfectGasWithSupportApplyEOSWithSupportExecutionContext("ApplyEOSWithSupportExecutionContext", &vars));\
SciHook::trigger(APPLYEOSWITHSUPPORT_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOSWITHSUPPORT_AFTER SciHook::trigger(APPLYEOSWITHSUPPORT_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOSWITHSUPPORT_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOSWITHSUPPORT_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_INITEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_INITEOS_BEFORE \
std::shared_ptr<PerfectGasWithSupportInitEOSExecutionContext> ctx(new PerfectGasWithSupportInitEOSExecutionContext("InitEOSExecutionContext", &vars, env));\
SciHook::trigger(INITEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_INITEOS_AFTER SciHook::trigger(INITEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_INITEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_INITEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOS_BEFORE \
std::shared_ptr<PerfectGasWithSupportApplyEOSExecutionContext> ctx(new PerfectGasWithSupportApplyEOSExecutionContext("ApplyEOSExecutionContext", env));\
SciHook::trigger(APPLYEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOS_AFTER SciHook::trigger(APPLYEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYEOS_AFTER
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_DISABLED) && not defined(SCIHOOK_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYONECELLEOS_DISABLED)
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYONECELLEOS_BEFORE \
std::shared_ptr<PerfectGasWithSupportApplyOneCellEOSExecutionContext> ctx(new PerfectGasWithSupportApplyOneCellEOSExecutionContext("ApplyOneCellEOSExecutionContext", &vars, env, ev));\
SciHook::trigger(APPLYONECELLEOS_BEFORE, ctx);
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYONECELLEOS_AFTER SciHook::trigger(APPLYONECELLEOS_AFTER, ctx);
#else
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYONECELLEOS_BEFORE
#define SCIHOOK_TRIGGER_EOS_PERFECTGAS_PERFECTGASWITHSUPPORT_APPLYONECELLEOS_AFTER
#endif

#endif // EOS_PERFECTGAS___PERFECTGASWITHSUPPORTSERVICESCIHOOKMACROS_H
