#ifndef REMAP_ALE___REMAPALESERVICESCIHOOKMACROS_H
#define REMAP_ALE___REMAPALESERVICESCIHOOKMACROS_H

#include "scihook/scihookdefs.h"
#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_REMAP_ALE_REMAPALE_DISABLED)
#include "SciHook.h"
#include "remap/ale/__RemapALEServiceContexts.h"
#endif

#if defined(SCIHOOK_ENABLED) && not defined(SCIHOOK_REMAP_ALE_REMAPALE_DISABLED)
#define SCIHOOK_DECLARE_REMAP_ALE_REMAPALE_EVENTS \
private:\
#define SCIHOOK_INITIALIZE_REMAP_ALE_REMAPALE_EVENTS \
#else
#define SCIHOOK_DECLARE_REMAP_ALE_REMAPALE_EVENTS
#define SCIHOOK_INITIALIZE_REMAP_ALE_REMAPALE_EVENTS
#endif

#endif // REMAP_ALE___REMAPALESERVICESCIHOOKMACROS_H
